imu_topic: /livox/imu
lidar_topic: /livox/lidar
body_frame: base_link
world_frame: lidar_odom
print_time_cost: false

lidar_filter_num: 3
lidar_min_range: 0.5
lidar_max_range: 20.0
scan_resolution: 0.15
map_resolution: 0.3

cube_len: 1000
det_range: 100
move_thresh: 1.5

na: 0.02
ng: 0.02
nba: 0.0002
nbg: 0.0002

imu_init_num: 15
near_search_num: 5
ieskf_max_iter: 5

gravity_align: true
esti_il: true

r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
t_il: [-0.011, -0.02329, 0.04412]

lidar_cov_inv: 1000.0
